DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS project;

CREATE TABLE status (
	id INT AUTO_INCREMENT NOT NULL, 
	project_id INT NOT NULL,
	stage VARCHAR(255) NOT NULL, 
	status LONGTEXT NOT NULL, 
	lastUpdated DATETIME DEFAULT NULL, 
	lastUpdatedBy VARCHAR(255) DEFAULT NULL, 
	PRIMARY KEY(id))
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE project (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	isArchived TINYINT(1) DEFAULT 0,
	UNIQUE INDEX (name),
	PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE status ADD FOREIGN KEY (project_id) REFERENCES project (id);